name: CI/CD Pipeline for Intframework

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Günlük olarak gece yarısı çalışacak

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
    - name: Install Framework
      run: |
        git clone https://github.com/Intikam21kurucu/intframework
        cd intframework
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cd ~
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

  notify:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Notify deployment status
      uses: actions/github-script@v6
      with:
        script: |
          console.log("hi im inttable!")